# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/SicDataMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/SicDataMessage.proto',
  package='org.apache.camel.component.protobuf',
  syntax='proto3',
  serialized_options=b'\n#org.apache.camel.component.protobufB\017SicDataMessages',
  serialized_pb=b'\n\x1aproto/SicDataMessage.proto\x12#org.apache.camel.component.protobuf\",\n\x0eSicDataMessage\x12\x0b\n\x03UID\x18\x01 \x01(\t\x12\r\n\x05\x62\x44\x61ta\x18\x02 \x01(\x0c\x42\x36\n#org.apache.camel.component.protobufB\x0fSicDataMessagesb\x06proto3'
)




_SICDATAMESSAGE = _descriptor.Descriptor(
  name='SicDataMessage',
  full_name='org.apache.camel.component.protobuf.SicDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UID', full_name='org.apache.camel.component.protobuf.SicDataMessage.UID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bData', full_name='org.apache.camel.component.protobuf.SicDataMessage.bData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['SicDataMessage'] = _SICDATAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SicDataMessage = _reflection.GeneratedProtocolMessageType('SicDataMessage', (_message.Message,), {
  'DESCRIPTOR' : _SICDATAMESSAGE,
  '__module__' : 'proto.SicDataMessage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.camel.component.protobuf.SicDataMessage)
  })
_sym_db.RegisterMessage(SicDataMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
