// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SicDataMessage.proto

package org.apache.camel.component.protobuf;

public final class SicDataMessages {
  private SicDataMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SicDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.camel.component.protobuf.SicDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string UID = 1;</code>
     * @return The uID.
     */
    java.lang.String getUID();
    /**
     * <code>string UID = 1;</code>
     * @return The bytes for uID.
     */
    com.google.protobuf.ByteString
        getUIDBytes();

    /**
     * <code>bytes bData = 2;</code>
     * @return The bData.
     */
    com.google.protobuf.ByteString getBData();
  }
  /**
   * Protobuf type {@code org.apache.camel.component.protobuf.SicDataMessage}
   */
  public  static final class SicDataMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.apache.camel.component.protobuf.SicDataMessage)
      SicDataMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SicDataMessage.newBuilder() to construct.
    private SicDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SicDataMessage() {
      uID_ = "";
      bData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SicDataMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SicDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uID_ = s;
              break;
            }
            case 18: {

              bData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.camel.component.protobuf.SicDataMessages.internal_static_org_apache_camel_component_protobuf_SicDataMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.camel.component.protobuf.SicDataMessages.internal_static_org_apache_camel_component_protobuf_SicDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage.class, org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uID_;
    /**
     * <code>string UID = 1;</code>
     * @return The uID.
     */
    public java.lang.String getUID() {
      java.lang.Object ref = uID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uID_ = s;
        return s;
      }
    }
    /**
     * <code>string UID = 1;</code>
     * @return The bytes for uID.
     */
    public com.google.protobuf.ByteString
        getUIDBytes() {
      java.lang.Object ref = uID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bData_;
    /**
     * <code>bytes bData = 2;</code>
     * @return The bData.
     */
    public com.google.protobuf.ByteString getBData() {
      return bData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uID_);
      }
      if (!bData_.isEmpty()) {
        output.writeBytes(2, bData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uID_);
      }
      if (!bData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage)) {
        return super.equals(obj);
      }
      org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage other = (org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage) obj;

      if (!getUID()
          .equals(other.getUID())) return false;
      if (!getBData()
          .equals(other.getBData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUID().hashCode();
      hash = (37 * hash) + BDATA_FIELD_NUMBER;
      hash = (53 * hash) + getBData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.camel.component.protobuf.SicDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.camel.component.protobuf.SicDataMessage)
        org.apache.camel.component.protobuf.SicDataMessages.SicDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.camel.component.protobuf.SicDataMessages.internal_static_org_apache_camel_component_protobuf_SicDataMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.camel.component.protobuf.SicDataMessages.internal_static_org_apache_camel_component_protobuf_SicDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage.class, org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage.Builder.class);
      }

      // Construct using org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uID_ = "";

        bData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.camel.component.protobuf.SicDataMessages.internal_static_org_apache_camel_component_protobuf_SicDataMessage_descriptor;
      }

      @java.lang.Override
      public org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage getDefaultInstanceForType() {
        return org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage build() {
        org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage buildPartial() {
        org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage result = new org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage(this);
        result.uID_ = uID_;
        result.bData_ = bData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage) {
          return mergeFrom((org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage other) {
        if (other == org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage.getDefaultInstance()) return this;
        if (!other.getUID().isEmpty()) {
          uID_ = other.uID_;
          onChanged();
        }
        if (other.getBData() != com.google.protobuf.ByteString.EMPTY) {
          setBData(other.getBData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uID_ = "";
      /**
       * <code>string UID = 1;</code>
       * @return The uID.
       */
      public java.lang.String getUID() {
        java.lang.Object ref = uID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string UID = 1;</code>
       * @return The bytes for uID.
       */
      public com.google.protobuf.ByteString
          getUIDBytes() {
        java.lang.Object ref = uID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string UID = 1;</code>
       * @param value The uID to set.
       * @return This builder for chaining.
       */
      public Builder setUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string UID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUID() {
        
        uID_ = getDefaultInstance().getUID();
        onChanged();
        return this;
      }
      /**
       * <code>string UID = 1;</code>
       * @param value The bytes for uID to set.
       * @return This builder for chaining.
       */
      public Builder setUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uID_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bData = 2;</code>
       * @return The bData.
       */
      public com.google.protobuf.ByteString getBData() {
        return bData_;
      }
      /**
       * <code>bytes bData = 2;</code>
       * @param value The bData to set.
       * @return This builder for chaining.
       */
      public Builder setBData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBData() {
        
        bData_ = getDefaultInstance().getBData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.apache.camel.component.protobuf.SicDataMessage)
    }

    // @@protoc_insertion_point(class_scope:org.apache.camel.component.protobuf.SicDataMessage)
    private static final org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage();
    }

    public static org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SicDataMessage>
        PARSER = new com.google.protobuf.AbstractParser<SicDataMessage>() {
      @java.lang.Override
      public SicDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SicDataMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SicDataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SicDataMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.apache.camel.component.protobuf.SicDataMessages.SicDataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_camel_component_protobuf_SicDataMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_camel_component_protobuf_SicDataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/SicDataMessage.proto\022#org.apache" +
      ".camel.component.protobuf\",\n\016SicDataMess" +
      "age\022\013\n\003UID\030\001 \001(\t\022\r\n\005bData\030\002 \001(\014B6\n#org.a" +
      "pache.camel.component.protobufB\017SicDataM" +
      "essagesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_apache_camel_component_protobuf_SicDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_camel_component_protobuf_SicDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_camel_component_protobuf_SicDataMessage_descriptor,
        new java.lang.String[] { "UID", "BData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
